### ISSUE TITLE
move over DNS entry for `ci.concourse-ci.org`

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/prod#39]
Tentative plans:

Pre-work:
- merge https://github.com/concourse/ci/pull/231
- merge https://github.com/concourse/hush-house/pull/90
- [Figure out prod deploys](https://github.com/concourse/ci/issues/192#issuecomment-563330326): https://github.com/concourse/prod/issues/45
    - [ ] [windows worker on prod](https://github.com/concourse/prod/blob/master/deployments/windows_worker.yml) should move its config to `ci`

PR to concourse/prod:
- [x] remove `ci-concourse-ci-org-dns` from https://github.com/concourse/prod/blob/master/iaas/dns.tf

PR to concourse/ci:
- [x] topgun worker - update configuration in concourse/ci with new DNS
- [x] k8s-topgun worker - update configuration in `ci` with new DNS
- [x] windows worker - update configuration in `ci` with new DNS
- [x] [concourse-pipeline resource](https://github.com/concourse/ci/blob/master/pipelines/reconfigure.yml) inside the reconfigure pipeline
- [x] slack notification resource inside the main pipeline

PR to concourse/hush-house:
- [x] change `concourse-nci-address` in https://github.com/concourse/hush-house/blob/master/terraform/main.tf
- [x] [external url on the new environment](https://github.com/concourse/hush-house/blob/master/deployments/with-creds/ci/values.yaml) needs to change too
- [x] change cluster name from `ci-house` to `ci`

Secrets:
- [x] TLS cert on API/web

manual followup steps:
- [x] `terraform apply` in `prod`
- [x] `terraform apply` in `hush-house`
- [x] deploy CI and all its worker pools, using the results of #45
- [x] github auth redirect url

**Comment by pivotal-jamie-klassen** [comment]
potentially TLS certificates need to be updated as well

**Comment by vito** [comment]
This is done now but it was a bit clunky getting everything up to date. I've created a new epic, [Greenpeace](https://project.concourse-ci.org/projects/MDc6UHJvamVjdDM3ODExNjE=), for cleaning up our environments. Let's track high level goals here and try to tackle this some time soon.
