### ISSUE TITLE
logging solution for k8s ci

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/prod#40]
add a wiki entry for how to search for logs in stackdriver - can it be as easy as papertrail?

**Comment by cirocosta** [comment]
@vito documented the filter for us!

<img width="606" alt="Screen Shot 2020-02-10 at 4 13 02 PM" src="https://user-images.githubusercontent.com/3574444/74190369-3e883600-4c20-11ea-865b-3f4127ac277a.png">

https://concourse.github.io/boarding-pass/hush-house.html
