### ISSUE TITLE
continuously deploy bosh-topgun worker in main pipeline

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/prod#43]
similar to pks worker, tag everything to do with topgun or that worker appropriately.... you should be able to still use the bosh-deployment resource. the manifest for that worker is in concourse/prod, called something like `topgun-worker.yml`

**Comment by taylorsilva** [comment]
Work is happening in branch `topgun-worker-deployment`
https://github.com/concourse/ci/tree/topgun-worker-deployment

Strategy is to add a `put` step to the `bbl` environment where the bosh-topgun worker lives.
