### ISSUE TITLE
set up auto-unseal for vault

### ISSUE THREAD

**Issue by zoetian** [concourse/prod#48]
- [x] auto-unseal 
   - [x] Understand auto-unseal with Google Cloud Key Management Service ([extraEnvVars in values.yaml](https://github.com/hashicorp/vault-helm/blob/faf5a84c5e9e9dd18d4ba6b914b37e356c6022ab/values.yaml#L62-L67) from the chart `vault-helm` and [auto-unseal settings in vault config file](https://github.com/hashicorp/vault-helm/blob/faf5a84c5e9e9dd18d4ba6b914b37e356c6022ab/values.yaml#L196-L204), 
   - [x] [sample terraform config for gcpkms](https://github.com/hashicorp/vault-helm/blob/0342358c945b247ba772c89ca97517123fafca99/test/terraform/main.tf#L25-L37) and  [terraform docs for gcpkms](https://www.terraform.io/docs/providers/google/r/kms_key_ring.html)
  - [x] terraform update with adding `gkms` crypto and key ring.
  - [x] add gcp credential to `hush-house-values-nci` in `lastpass`.
  - [x] run command `vault operator init` to initialize vault.

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**

Today I:
- populated `gkms` into terraform script.
- added vault keys into `lastpass`
- added a new template for `gcp` credential
- tuned the config script to make auto-unseal work
- created a draft PR https://github.com/concourse/hush-house/pull/89

**NEXT**:
None
